In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("height-weight.csv")

In [ ]:
df

       Index  Height(Inches)  Weight(Pounds)
0          1        65.78331        112.9925
1          2        71.51521        136.4873
2          3        69.39874        153.0269
3          4        68.21660        142.3354
4          5        67.78781        144.2971
...      ...             ...             ...
24995  24996        69.50215        118.0312
24996  24997        64.54826        120.1932
24997  24998        64.69855        118.2655
24998  24999        67.52918        132.2682
24999  25000        68.87761        124.8742

[25000 rows x 3 columns]

In [ ]:
df.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [ ]:
df.tail()

       Index  Height(Inches)  Weight(Pounds)
24995  24996        69.50215        118.0312
24996  24997        64.54826        120.1932
24997  24998        64.69855        118.2655
24998  24999        67.52918        132.2682
24999  25000        68.87761        124.8742

In [ ]:
#divide into x and y
#x-input feature and y-output feature
x=df[['Height(Inches)']]
y=df[['Weight(Pounds)']]

In [ ]:
df.isnull().sum()

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [ ]:
df.isnull().any()

Index             False
Height(Inches)    False
Weight(Pounds)    False
dtype: bool

In [ ]:
#learning -> cyclic learning
#libraries most used -> tensor flow and pytorch in ML
#cmon-> graph library

In [ ]:
from sklearn.model_selection import train_test_split

This line imports the train_test_split function from the model_selection module of the Python library scikit-learn.

Breakdown
sklearn → Short name for Scikit-learn
model_selection → Module used for splitting and selecting data for machine learning models
train_test_split → Function used to divide data into:
Training data → used to train the model
Testing data → used to test model accuracy

Why we use it

In Machine Learning, we should not train and test using the same data.

So we split the dataset like this:

80% → Training
20% → Testing
Example

variable1, variable2, variable3, variable4 = train_test_split(input_data, output_data, test_size=value)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

       Height(Inches)
12637        70.12075
1739         65.02676
4556         70.01907
3762         68.09648
785          67.43294
...               ...
10506        68.17200
8385         69.18567
3741         68.67678
7296         66.67637
20384        67.85068

[20000 rows x 1 columns]

In [ ]:
x_test

       Height(Inches)
22895        67.50031
23871        64.61346
10003        66.78394
7144         67.73615
23774        67.67603
...               ...
87           70.09297
12535        66.89099
654          71.23576
11374        67.01918
8448         70.02024

[5000 rows x 1 columns]

In [ ]:
#import the model -- linear regression

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression() #MODEL SELECTED

In [ ]:
#train the model by using the fit
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
#test the model by using the predict
y_pred=model.predict(x_test)

In [ ]:
y_test

       Weight(Pounds)
22895        118.3179
23871        103.4199
10003        128.5766
7144         130.1305
23774        124.4685
...               ...
87           131.5916
12535        137.6137
654          140.2945
11374        131.7105
8448         140.0166

[5000 rows x 1 columns]

In [ ]:
#subtract the val to know whether it is correct or not - using metrices ( to check error and accuracy)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score;

In [ ]:
mean_absolute_error(y_test,y_pred)

8.046675645178807

In [ ]:
mean_squared_error(y_test,y_pred)

102.50817030319996

In [ ]:
r2_score(y_test,y_pred)
#accuracy score : ans correctly 25%

0.25047962779328337

In [ ]:
#To save the model

In [ ]:
import joblib

In [ ]:
joblib.dump(model,"linear.pkl")

['linear.pkl']

In [ ]:
model_copy=joblib.load("linear.pkl")

In [ ]:
model_copy.predict([[100]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[225.46128606]])

# pyspark

In [ ]:
#install pyspark
!pip install pyspark --quiet

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import year,month,to_date,round as spark_round

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#create session

In [ ]:
spark=SparkSession.builder \
.appName('Day4_BigData_Sales') \
.config('spark.sql.adaptive.enabled','true') \
.getOrCreate() #create or reuse xsession

In [ ]:
print(spark.version)
print("Spark session active")
print(spark.sparkContext.appName)

4.0.2
Spark session active
Day4_BigData_Sales

In [ ]:
#load the large dataset

In [ ]:
df_bronze=spark.read \
.option('header','true') \
.option('inferSchema','true') \
.csv('/content/large_sales_data.csv')

In [ ]:
#above header true means there is a presence of cols
#above inferSchema true means autodetect the data type

In [ ]:
df_bronze.count()

5000

In [ ]:
len(df_bronze.columns)

13

In [ ]:
df_bronze.columns

['order_id',
 'customer_name',
 'product',
 'category',
 'quantity',
 'unit_price',
 'revenue',
 'order_date',
 'city',
 'region',
 'sales_rep',
 'payment_method',
 'order_status']

In [ ]:
#truncate false na , show all the string without cutting
df_bronze.show(5,truncate=False)

+--------+-------------+----------+-----------+--------+----------+-------+----------+---------+------+-----------+----------------+------------+
|order_id|customer_name|product   |category   |quantity|unit_price|revenue|order_date|city     |region|sales_rep  |payment_method  |order_status|
+--------+-------------+----------+-----------+--------+----------+-------+----------+---------+------+-----------+----------------+------------+
|1001    |Sneha Reddy  |Monitor   |Electronics|12      |22000     |264000 |2023-05-21|Mumbai   |West  |Meera Patel|UPI             |Delivered   |
|1002    |Ramesh Kumar |Printer   |Electronics|10      |12000     |120000 |2023-08-05|Delhi    |North |Anil Sharma|Credit Card     |Shipped     |
|1003    |Rahul Mishra |Mouse     |Accessories|10      |800       |8000   |2023-01-14|Ahmedabad|West  |Meera Patel|Cash on Delivery|Shipped     |
|1004    |Suresh Rao   |Tablet    |Electronics|5       |32000     |160000 |2023-01-04|Surat    |West  |Ravi Kumar |Cash on Delivery|Processing  |
|1005    |Priya Patel  |Headphones|Electronics|4       |3500      |14000  |2023-06-22|Bangalore|South |Sunita Rao |Cash on Delivery|Delivered   |
+--------+-------------+----------+-----------+--------+----------+-------+----------+---------+------+-----------+----------------+------------+
only showing top 5 rows

In [ ]:
#select udes to select the col and describe(max,min,avg) and show to print
df_bronze.select('quantity','unit_price','revenue').describe().show()

+-------+-----------------+------------------+------------------+
|summary|         quantity|        unit_price|           revenue|
+-------+-----------------+------------------+------------------+
|  count|             5000|              5000|              5000|
|   mean|           7.9536|          12496.86|          99169.52|
| stddev|4.275313169878912|14857.384309295603|145972.97195261103|
|    min|                1|               600|               600|
|    max|               15|             45000|            675000|
+-------+-----------------+------------------+------------------+

In [ ]:
#mode overwrite means directly replace the exist
#parquet means its like csv
df_bronze.write \
.mode('overwrite') \
.parquet('sales_bronze.parquet')

In [ ]:

import os

Assignment

In [ ]:
df1=pd.read_csv("")