In [1]:
!pip install requests --quiet

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import requests

In [5]:
import matplotlib.pyplot as plt

In [6]:
import warnings
warnings.filterwarnings('ignore')

In [7]:
print(pd.__version__)
print(requests.__version__)

2.2.2
2.32.4

# ETL

**activity 1 - Clean messy_sales_data.csv**

upload the file and run the cell

1. Missing values in customer_name, quantity, category

2. Duplicate rows (orders 1001/1005 are identical)

3. Mixed data formates: YYYY-MM-DD and DD_MM-YYYY

4. Inconsistent test case in customer_name (UPPER,lower,Title)

5. Wrong category values(Keyboard labelled as Electronics)

In [8]:
df=pd.read_csv("messy_sales_data.csv")

In [9]:
df.shape

(30, 9)

In [10]:
df.shape[0]

30

In [11]:
df.shape[1]

9

In [12]:
df.columns.tolist()

['order_id',
 'customer_name',
 'product',
 'category',
 'quantity',
 'unit_price',
 'order_date',
 'city',
 'sales_rep']

In [13]:
df.head()

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [14]:
df

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
5,1006,kiran mehta,Mouse,Accessories,10.0,800,07-01-2024,Pune,Sunita Rao
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,2024-01-12,Hyderabad,Ravi Kumar
7,1008,NaN,Webcam,Accessories,1.0,2500,2024-01-13,Mumbai,Anil Sharma
8,1009,Ananya Das,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao
9,1010,Vikram Iyer,Keyboard,Accessories,5.0,1200,2024-01-15,Chennai,Ravi Kumar
10,1011,Pooja Gupta,Monitor,Electronics,2.0,22000,2024-01-18,Delhi,Anil Sharma
11,1012,SURESH RAO,USB Hub,Accessories,8.0,600,2024-01-20,Bangalore,Sunita Rao
12,1013,Meera Joshi,Laptop,Electronics,NaN,45000,2024-01-22,Pune,Ravi Kumar
13,1014,Arjun Nair,Headphones,Electronics,3.0,3500,21-01-2024,Kochi,Anil Sharma
14,1015,Tanvi Mehta,Webcam,Accessories,2.0,2500,2024-01-25,Surat,Sunita Rao
15,1016,Kiran Mehta,Mouse,Accessories,10.0,800,2024-01-07,Pune,Sunita Rao
16,1017,Deepak Singh,Keyboard,Accessories,5.0,1200,2024-01-28,Hyderabad,Ravi Kumar
17,1018,Rohit Verma,Monitor,Electronics,1.0,22000,2024-01-30,Delhi,Anil Sharma
18,1019,Sneha Reddy,Laptop,Electronics,1.0,45000,2024-02-01,Hyderabad,Ravi Kumar
19,1020,Gaurav Shukla,USB Hub,Accessories,15.0,600,2024-02-03,Lucknow,Sunita Rao
20,1021,Nisha Kapoor,Headphones,Electronics,2.0,3500,2024-02-05,Chandigarh,Anil Sharma
21,1022,Ajay Tiwari,Webcam,Accessories,3.0,2500,2024-02-07,Bhopal,Ravi Kumar
22,1023,ANANYA DAS,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao
23,1024,Preeti Saxena,Keyboard,Electronics,4.0,1200,2024-02-10,Kanpur,Anil Sharma
24,1025,Amit Bose,Mouse,Accessories,6.0,800,2024-02-12,Kolkata,Sunita Rao
25,1026,NaN,Headphones,Electronics,1.0,3500,2024-02-14,Mumbai,Ravi Kumar
26,1027,Rekha Nair,Monitor,NaN,2.0,22000,2024-02-15,Kochi,Anil Sharma
27,1028,Harish Pillai,Laptop,Electronics,3.0,45000,2024-02-18,Thiruvananthapuram,Ravi Kumar
28,1029,Sanjay Dubey,USB Hub,Accessories,10.0,600,2024-02-20,Allahabad,Sunita Rao
29,1030,Kavya Nambiar,Webcam,Accessories,NaN,2500,2024-02-22,Thrissur,Anil Sharma

In [15]:
#Missing values
df.isnull().sum()

order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

In [16]:
#Duplicate Values
df.duplicated().sum()

np.int64(0)

In [17]:
#Data types
df.dtypes

order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

In [18]:
#Unique values in the category column
df['category'].unique()

array(['Electronics', 'Accessories', nan], dtype=object)

In [19]:
df['customer_name']

0      Ramesh Kumar
1        Priya Nair
2        AMIT VERMA
3      Sunita Patel
4      Ramesh Kumar
5       kiran mehta
6      Deepak Singh
7               NaN
8        Ananya Das
9       Vikram Iyer
10      Pooja Gupta
11       SURESH RAO
12      Meera Joshi
13       Arjun Nair
14      Tanvi Mehta
15      Kiran Mehta
16     Deepak Singh
17      Rohit Verma
18      Sneha Reddy
19    Gaurav Shukla
20     Nisha Kapoor
21      Ajay Tiwari
22       ANANYA DAS
23    Preeti Saxena
24        Amit Bose
25              NaN
26       Rekha Nair
27    Harish Pillai
28     Sanjay Dubey
29    Kavya Nambiar
Name: customer_name, dtype: object

In [20]:
#Remove the null value by dropna and show the unique names by unique
df['customer_name'].dropna().unique()[:30]

array(['Ramesh Kumar', 'Priya Nair', 'AMIT VERMA', 'Sunita Patel',
       'kiran mehta', 'Deepak Singh', 'Ananya Das', 'Vikram Iyer',
       'Pooja Gupta', 'SURESH RAO', 'Meera Joshi', 'Arjun Nair',
       'Tanvi Mehta', 'Kiran Mehta', 'Rohit Verma', 'Sneha Reddy',
       'Gaurav Shukla', 'Nisha Kapoor', 'Ajay Tiwari', 'ANANYA DAS',
       'Preeti Saxena', 'Amit Bose', 'Rekha Nair', 'Harish Pillai',
       'Sanjay Dubey', 'Kavya Nambiar'], dtype=object)

In [21]:
#show the null value also
df['customer_name'].unique()[:20]

array(['Ramesh Kumar', 'Priya Nair', 'AMIT VERMA', 'Sunita Patel',
       'kiran mehta', 'Deepak Singh', nan, 'Ananya Das', 'Vikram Iyer',
       'Pooja Gupta', 'SURESH RAO', 'Meera Joshi', 'Arjun Nair',
       'Tanvi Mehta', 'Kiran Mehta', 'Rohit Verma', 'Sneha Reddy',
       'Gaurav Shukla', 'Nisha Kapoor', 'Ajay Tiwari'], dtype=object)

In [22]:
df['order_date'].unique()[:20]

array(['2024-01-05', '2024-01-07', '2024-01-08', '2024-01-10',
       '07-01-2024', '2024-01-12', '2024-01-13', '2024-01-15',
       '2024-01-18', '2024-01-20', '2024-01-22', '21-01-2024',
       '2024-01-25', '2024-01-28', '2024-01-30', '2024-02-01',
       '2024-02-03', '2024-02-05', '2024-02-07', '2024-02-10'],
      dtype=object)

In [23]:
#copy the df to not miss the actual data
cdf=df.copy()

In [24]:
cdf

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
5,1006,kiran mehta,Mouse,Accessories,10.0,800,07-01-2024,Pune,Sunita Rao
6,1007,Deepak Singh,Headphones,Electronics,2.0,3500,2024-01-12,Hyderabad,Ravi Kumar
7,1008,NaN,Webcam,Accessories,1.0,2500,2024-01-13,Mumbai,Anil Sharma
8,1009,Ananya Das,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao
9,1010,Vikram Iyer,Keyboard,Accessories,5.0,1200,2024-01-15,Chennai,Ravi Kumar
10,1011,Pooja Gupta,Monitor,Electronics,2.0,22000,2024-01-18,Delhi,Anil Sharma
11,1012,SURESH RAO,USB Hub,Accessories,8.0,600,2024-01-20,Bangalore,Sunita Rao
12,1013,Meera Joshi,Laptop,Electronics,NaN,45000,2024-01-22,Pune,Ravi Kumar
13,1014,Arjun Nair,Headphones,Electronics,3.0,3500,21-01-2024,Kochi,Anil Sharma
14,1015,Tanvi Mehta,Webcam,Accessories,2.0,2500,2024-01-25,Surat,Sunita Rao
15,1016,Kiran Mehta,Mouse,Accessories,10.0,800,2024-01-07,Pune,Sunita Rao
16,1017,Deepak Singh,Keyboard,Accessories,5.0,1200,2024-01-28,Hyderabad,Ravi Kumar
17,1018,Rohit Verma,Monitor,Electronics,1.0,22000,2024-01-30,Delhi,Anil Sharma
18,1019,Sneha Reddy,Laptop,Electronics,1.0,45000,2024-02-01,Hyderabad,Ravi Kumar
19,1020,Gaurav Shukla,USB Hub,Accessories,15.0,600,2024-02-03,Lucknow,Sunita Rao
20,1021,Nisha Kapoor,Headphones,Electronics,2.0,3500,2024-02-05,Chandigarh,Anil Sharma
21,1022,Ajay Tiwari,Webcam,Accessories,3.0,2500,2024-02-07,Bhopal,Ravi Kumar
22,1023,ANANYA DAS,Laptop,Electronics,1.0,45000,2024-01-15,Kolkata,Sunita Rao
23,1024,Preeti Saxena,Keyboard,Electronics,4.0,1200,2024-02-10,Kanpur,Anil Sharma
24,1025,Amit Bose,Mouse,Accessories,6.0,800,2024-02-12,Kolkata,Sunita Rao
25,1026,NaN,Headphones,Electronics,1.0,3500,2024-02-14,Mumbai,Ravi Kumar
26,1027,Rekha Nair,Monitor,NaN,2.0,22000,2024-02-15,Kochi,Anil Sharma
27,1028,Harish Pillai,Laptop,Electronics,3.0,45000,2024-02-18,Thiruvananthapuram,Ravi Kumar
28,1029,Sanjay Dubey,USB Hub,Accessories,10.0,600,2024-02-20,Allahabad,Sunita Rao
29,1030,Kavya Nambiar,Webcam,Accessories,NaN,2500,2024-02-22,Thrissur,Anil Sharma

In [25]:
df.isnull().sum().sum()

np.int64(7)

In [26]:
df['customer_name'].fillna('Unknown Customer',inplace=True)

In [27]:
df['customer_name'].tolist()

['Ramesh Kumar',
 'Priya Nair',
 'AMIT VERMA',
 'Sunita Patel',
 'Ramesh Kumar',
 'kiran mehta',
 'Deepak Singh',
 'Unknown Customer',
 'Ananya Das',
 'Vikram Iyer',
 'Pooja Gupta',
 'SURESH RAO',
 'Meera Joshi',
 'Arjun Nair',
 'Tanvi Mehta',
 'Kiran Mehta',
 'Deepak Singh',
 'Rohit Verma',
 'Sneha Reddy',
 'Gaurav Shukla',
 'Nisha Kapoor',
 'Ajay Tiwari',
 'ANANYA DAS',
 'Preeti Saxena',
 'Amit Bose',
 'Unknown Customer',
 'Rekha Nair',
 'Harish Pillai',
 'Sanjay Dubey',
 'Kavya Nambiar']

In [28]:
median_qty=df['quantity'].median()

In [29]:
df['quantity'].isnull().sum()

np.int64(3)

In [30]:
df['quantity'].fillna(median_qty,inplace=True)

In [31]:
df['quantity'].tolist()

[2.0,
 1.0,
 3.0,
 2.0,
 2.0,
 10.0,
 2.0,
 1.0,
 1.0,
 5.0,
 2.0,
 8.0,
 2.0,
 3.0,
 2.0,
 10.0,
 5.0,
 1.0,
 1.0,
 15.0,
 2.0,
 3.0,
 1.0,
 4.0,
 6.0,
 1.0,
 2.0,
 3.0,
 10.0,
 2.0]

In [32]:
df['category'].isnull().sum()

np.int64(1)

In [33]:
df['category'].tolist()

['Electronics',
 'Electronics',
 'Accessories',
 'Electronics',
 'Electronics',
 'Accessories',
 'Electronics',
 'Accessories',
 'Electronics',
 'Accessories',
 'Electronics',
 'Accessories',
 'Electronics',
 'Electronics',
 'Accessories',
 'Accessories',
 'Accessories',
 'Electronics',
 'Electronics',
 'Accessories',
 'Electronics',
 'Accessories',
 'Electronics',
 'Electronics',
 'Accessories',
 'Electronics',
 nan,
 'Electronics',
 'Accessories',
 'Accessories']

In [34]:
df['category'].fillna("Uncategorized",inplace=True)

In [35]:
df['category']

0       Electronics
1       Electronics
2       Accessories
3       Electronics
4       Electronics
5       Accessories
6       Electronics
7       Accessories
8       Electronics
9       Accessories
10      Electronics
11      Accessories
12      Electronics
13      Electronics
14      Accessories
15      Accessories
16      Accessories
17      Electronics
18      Electronics
19      Accessories
20      Electronics
21      Accessories
22      Electronics
23      Electronics
24      Accessories
25      Electronics
26    Uncategorized
27      Electronics
28      Accessories
29      Accessories
Name: category, dtype: object

In [36]:
df['product']

0         Laptop
1            NaN
2       Keyboard
3        Monitor
4         Laptop
5          Mouse
6     Headphones
7         Webcam
8         Laptop
9       Keyboard
10       Monitor
11       USB Hub
12        Laptop
13    Headphones
14        Webcam
15         Mouse
16      Keyboard
17       Monitor
18        Laptop
19       USB Hub
20    Headphones
21        Webcam
22        Laptop
23      Keyboard
24         Mouse
25    Headphones
26       Monitor
27        Laptop
28       USB Hub
29        Webcam
Name: product, dtype: object

In [37]:
df['product'].fillna('Unknown Product',inplace=True)

In [38]:
df.isnull().sum().sum()

np.int64(0)

In [39]:
#remove the duplicated values

In [40]:
#Length of the table
len(df)

30

In [41]:
#Length of the duplicate rows
df.duplicated().sum()

np.int64(0)

In [42]:
#Keep false marks all copies of duplicate
#this will compare before and after (original and duplicate before removing)
print(df[df.duplicated(keep=False)][['order_id','customer_name','product','order_date']])

Empty DataFrame
Columns: [order_id, customer_name, product, order_date]
Index: []

In [43]:
#Check any duplicated rows are removed
print(len(df))
print(len(cdf)-len(df))

30
0

In [44]:
#Hence no rows are removed

In [45]:
#Date formating in the col

In [46]:
#just print the date col
print(df['order_date'].head(8).tolist())

['2024-01-05', '2024-01-07', '2024-01-08', '2024-01-10', '2024-01-05', '07-01-2024', '2024-01-12', '2024-01-13']

In [47]:
#Parsing operation to format the data
df['order_date']=pd.to_datetime(
    df['order_date'],
    dayfirst=False, #year at first
    errors='coerce' #Nat error appear if not able to format, to rectify the error
)

In [48]:
#count if there is any null values after the data format operation
n_count=df['order_date'].isnull().sum()
print(n_count)

2

In [49]:

df['year']=df['order_date'].dt.year
df['month'] =df['order_date'].dt.month
df['month_name']=df['order_date'].dt.strftime('%B')

In [50]:
print(df[['order_date','year','month','month_name']].head())

  order_date    year  month month_name
0 2024-01-05  2024.0    1.0    January
1 2024-01-07  2024.0    1.0    January
2 2024-01-08  2024.0    1.0    January
3 2024-01-10  2024.0    1.0    January
4 2024-01-05  2024.0    1.0    January

In [51]:
#Standarize or Customize the names

In [52]:
df['customer_name']=(
    df['customer_name']
    .str.strip() #removing the leading/trailing space
    .str.title() #Convert to Title Case "adit varma" to "Adit Varma"
)

In [53]:
#Remove the category keyboard because which is under the electronics category

In [54]:
df['category'].unique().tolist()

['Electronics', 'Accessories', 'Uncategorized']

In [55]:
print(df['customer_name'].unique()[:6])

['Ramesh Kumar' 'Priya Nair' 'Amit Verma' 'Sunita Patel' 'Kiran Mehta'
 'Deepak Singh']

In [56]:
wrong_mask=(df['product']=='Keyboard') &(df['category']=='Electronics')

In [57]:
print(df[wrong_mask][['product','category']])

     product     category
23  Keyboard  Electronics

In [58]:
df.loc[wrong_mask,'category']='Accessories'

In [59]:
df['category'].unique()

array(['Electronics', 'Accessories', 'Uncategorized'], dtype=object)

In [60]:
#Ensure the numeric cols quantity,unit pace has int type
df['quantity']=pd.to_numeric(df['quantity'],errors='coerce')
df['unit_price']=pd.to_numeric(df['unit_price'],errors='coerce')

In [61]:
#create the revenue column
df['revenue']=df['quantity']*df['unit_price']
df['revenue']

0      90000.0
1      15000.0
2       3600.0
3      44000.0
4      90000.0
5       8000.0
6       7000.0
7       2500.0
8      45000.0
9       6000.0
10     44000.0
11      4800.0
12     90000.0
13     10500.0
14      5000.0
15      8000.0
16      6000.0
17     22000.0
18     45000.0
19      9000.0
20      7000.0
21      7500.0
22     45000.0
23      4800.0
24      4800.0
25      3500.0
26     44000.0
27    135000.0
28      6000.0
29      5000.0
Name: revenue, dtype: float64

In [62]:
#just printing
df[['customer_name','product','quantity','unit_price','revenue']].head()

  customer_name          product  quantity  unit_price  revenue
0  Ramesh Kumar           Laptop       2.0       45000  90000.0
1    Priya Nair  Unknown Product       1.0       15000  15000.0
2    Amit Verma         Keyboard       3.0        1200   3600.0
3  Sunita Patel          Monitor       2.0       22000  44000.0
4  Ramesh Kumar           Laptop       2.0       45000  90000.0

In [63]:
#Print the total revenue
print(df['revenue'].sum())

818000.0

In [64]:
#Print all the details
print(f"Original rows: {len(cdf)}")
print(f"Cleaned rows: {len(df)}")
print(f"Row removed: {len(cdf)-len(df)}")
print(f"Missing values: {df.isnull().sum().sum()}")
print(f"Duplicate rows: {df.duplicated().sum()}")
print(f"Date nulls: {df["order_date"].isnull().sum()}")
print(f"Total revenue: {df['revenue'].isnull().sum()}")
print(f"Categories: {sorted(df['category'].unique())}")

allclean=(
    df.isnull().sum().sum()==0
    and df.duplicated().sum()==0
)
print(f"Data clean: {allclean}")

Original rows: 30
Cleaned rows: 30
Row removed: 0
Missing values: 8
Duplicate rows: 0
Date nulls: 2
Total revenue: 0
Categories: ['Accessories', 'Electronics', 'Uncategorized']
Data clean: False

transform -analyze

In [65]:
#For each product add the revenue amount
product_rev=(
    df.groupby('product') #group all rows by product name
    ['revenue'] #select the revenue col of each group
    .sum() #add the revenue for each group
    .sort_values(ascending=False) #sort to see the highest revenue
)

In [66]:
#print the above product_rev
print(f"Revenue by product: ")
print(product_rev)

Revenue by product:
product
Laptop             540000.0
Monitor            154000.0
Headphones          28000.0
Mouse               20800.0
Keyboard            20400.0
Webcam              20000.0
USB Hub             19800.0
Unknown Product     15000.0
Name: revenue, dtype: float64

In [67]:
#print
print(f"Revenue by product: ")
print(product_rev.to_string(index=False))

Revenue by product:
product
540000.0
154000.0
 28000.0
 20800.0
 20400.0
 20000.0
 19800.0
 15000.0

In [68]:
#Multi-metric aggregation using agg()
category_summary=df.groupby('category').agg(
    total_revenue=('revenue','sum'),
    avg_revenue=('revenue','mean'),
    min_revenue=('revenue','min'),
    max_revenue=('revenue','max'),
    count_product=('product','count')
).round(2).reset_index()

In [69]:
category_summary

,category,total_revenue,avg_revenue,min_revenue,max_revenue,count_product
0,Accessories,81000.0,5785.71,2500.0,9000.0,14
1,Electronics,693000.0,46200.00,3500.0,135000.0,15
2,Uncategorized,44000.0,44000.00,44000.0,44000.0,1

In [70]:
print(category_summary.to_string(index=False))

     category  total_revenue  avg_revenue  min_revenue  max_revenue  count_product
  Accessories        81000.0      5785.71       2500.0       9000.0             14
  Electronics       693000.0     46200.00       3500.0     135000.0             15
Uncategorized        44000.0     44000.00      44000.0      44000.0              1

In [71]:
df.to_csv('clean_sales_data.csv',index=False)

In [72]:
print('CLeaned data saved to: clean_sales_data.csv')
print(f'Final dataset: {df.shape[0]} rows * {df.shape[1]} columns')
print('\nETL Pipeline for Sales Data: COMPLETE')
print(' EXTRACT -> messy_sales_data.csv loaded')
print(' TRANSFORM -> messy_sales_data.csv cleaned')
print(' LOAD -> clean_sales_data.csv saved')

CLeaned data saved to: clean_sales_data.csv
Final dataset: 30 rows * 13 columns

ETL Pipeline for Sales Data: COMPLETE
 EXTRACT -> messy_sales_data.csv loaded
 TRANSFORM -> messy_sales_data.csv cleaned
 LOAD -> clean_sales_data.csv saved

In [73]:
#Configure API
API_KEY="74bf55a8588f5aea632feed8e4869df9"
BASE_URL="https://home.openweathermap.org/data/2.5/weather"
CITIES=['Mumbai','Delhi','Bangalore','Chennai','Hyderabad','Kolkata','Pune','Jaipur']
print(len(CITIES))
print(CITIES)

8
['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Hyderabad', 'Kolkata', 'Pune', 'Jaipur']

# Practice question
Q1.  What are the three stages of ETL? Describe each stage using an example from today's sales dataset

Q2.  A DataFrame has 500 rows. After calling df.dropna() it has 42 rows what does this tell you?

Q3.  Write code to remove deplicates from df where same row means same customer_name and same product

Q4.  What is the difference between fillna(0) and fillna(df['col'].median())? when would you perfer each?

Q5.  Write Python code to call the weather API for 'Delhi' and print the temperature in Celsius

Q6.What does response.status.code==200 mean? what should you do when the code is 401

---
# PART 2: Weather API ETL Pipeline

## Activity 2 — Call a Live API and Build a Pipeline

### What is an API?
**Level 1:** An API lets one software talk to another. You send a request, it sends back data.

**Level 2 (Waiter Analogy):** You (Python code) tell the waiter (API) what you want. The waiter fetches it from the kitchen (server) and brings it back as JSON.

**Level 3:** REST API — HTTP GET request with parameters → JSON response → parse into Python dict.

---
### Setup: Get a Free API Key
1. Go to: https://openweathermap.org/api
2. Sign up for a free account
3. Go to API keys section → copy your key
4. Paste it in the cell below

**Note:** If you do not have a key yet, a fallback dataset is provided below.

In [ ]:
# ============================================================
# CELL 13 — Configure API settings
# ============================================================

API_KEY = "you api paste here"
# Replace 'YOUR_API_KEY_HERE' with your actual OpenWeatherMap API key
# A free key allows 60 calls per minute — more than enough for this activity

BASE_URL = "https://api.openweathermap.org/data/2.5/weather"
# This is the API endpoint URL
# 'data/2.5/weather' = the specific API route for current weather

# Cities to query — 8 major Indian cities
CITIES = ['Mumbai', 'Delhi', 'Bangalore', 'Chennai',
          'Hyderabad', 'Kolkata', 'Pune', 'Jaipur']
# We will call the API once per city — 8 API calls total

print(f'API configured for {len(CITIES)} cities')
print(f'Cities: {CITIES}')
print('\nIMPORTANT: Replace YOUR_API_KEY_HERE with your actual key before running.')

API configured for 8 cities
Cities: ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Hyderabad', 'Kolkata', 'Pune', 'Jaipur']

IMPORTANT: Replace YOUR_API_KEY_HERE with your actual key before running.

In [ ]:
# ============================================================
# CELL 14 — EXTRACT: Call API for each city
# ============================================================
import requests;
def fetch_weather(city, API_KEY):
    """
    Fetch current weather data for a given city.
    Returns a dictionary with weather metrics, or None on failure.
    """
    params = {
        'q':     city,      # City name query parameter
        'appid': API_KEY,   # Authentication key
        'units': 'metric'   # Returns temperature in Celsius
    }
    # params is a dictionary — requests will encode it into the URL:
    # ?q=Mumbai&appid=KEY&units=metric

    try:
        response = requests.get(BASE_URL, params=params, timeout=10)
        # requests.get() sends an HTTP GET request to BASE_URL
        # timeout=10 — wait max 10 seconds; raise error if no response

        if response.status_code == 200:
            # status_code 200 = HTTP OK = request was successful
            data = response.json()
            # .json() parses the JSON text body into a Python dictionary

            return {
                'city':        city,
                'temperature': round(data['main']['temp'], 1),
                'feels_like':  round(data['main']['feels_like'], 1),
                'humidity':    data['main']['humidity'],
                'pressure':    data['main']['pressure'],
                'wind_speed':  data['wind']['speed'],
                'condition':   data['weather'][0]['description'].title(),
                'visibility':  data.get('visibility', 0) // 1000
                # .get('visibility', 0) — safe access: returns 0 if key missing
                # // 1000 — convert meters to kilometers (integer division)
            }
        else:
            print(f'  ERROR {response.status_code} for {city}: {response.json().get("message","unknown error")}')
            return None

    except requests.exceptions.ConnectionError:
        print(f'  CONNECTION ERROR for {city} — check internet connection')
        return None
    except requests.exceptions.Timeout:
        print(f'  TIMEOUT for {city} — API did not respond in 10 seconds')
        return None
    # try/except handles errors gracefully — one bad city doesn't crash the loop


# Call API for all cities
print('Calling Weather API...')
weather_records = []
# Empty list — we will append one dict per city

for city in CITIES:
    print(f'  Fetching: {city}...', end='')
    record = fetch_weather(city, API_KEY)
    if record:
        weather_records.append(record)
        # .append() adds the dict to our list
        print(f' {record["temperature"]}°C, {record["condition"]}')
    else:
        print(' FAILED')

print(f'\nSuccessfully fetched: {len(weather_records)}/{len(CITIES)} cities')

Calling Weather API...
  Fetching: Mumbai... 31.0°C, Haze
  Fetching: Delhi... 36.0°C, Haze
  Fetching: Bangalore... 24.6°C, Scattered Clouds
  Fetching: Chennai... 31.7°C, Haze
  Fetching: Hyderabad... 30.2°C, Haze
  Fetching: Kolkata... 27.0°C, Haze
  Fetching: Pune... 29.1°C, Scattered Clouds
  Fetching: Jaipur... 37.6°C, Haze

Successfully fetched: 8/8 cities

In [ ]:
# ============================================================
# CELL 15 — Fallback data (if API key not available)
# ============================================================
# Run this cell ONLY if weather_records is empty (API not working)

if len(weather_records) == 0:
    print('Using fallback weather data (API not available)')
    weather_records = [
        {'city':'Mumbai',    'temperature':32.5,'feels_like':36.0,'humidity':78,'pressure':1009,'wind_speed':5.2,'condition':'Partly Cloudy','visibility':8},
        {'city':'Delhi',     'temperature':38.2,'feels_like':41.0,'humidity':35,'pressure':1002,'wind_speed':3.8,'condition':'Clear Sky',    'visibility':10},
        {'city':'Bangalore', 'temperature':26.1,'feels_like':27.0,'humidity':62,'pressure':1016,'wind_speed':2.5,'condition':'Overcast',     'visibility':7},
        {'city':'Chennai',   'temperature':34.8,'feels_like':39.0,'humidity':72,'pressure':1008,'wind_speed':6.1,'condition':'Hazy',         'visibility':5},
        {'city':'Hyderabad', 'temperature':35.4,'feels_like':38.5,'humidity':45,'pressure':1005,'wind_speed':4.2,'condition':'Clear Sky',    'visibility':10},
        {'city':'Kolkata',   'temperature':33.7,'feels_like':37.8,'humidity':80,'pressure':1007,'wind_speed':4.8,'condition':'Humid',        'visibility':6},
        {'city':'Pune',      'temperature':29.3,'feels_like':31.0,'humidity':55,'pressure':1014,'wind_speed':3.1,'condition':'Partly Cloudy','visibility':9},
        {'city':'Jaipur',    'temperature':40.1,'feels_like':43.0,'humidity':22,'pressure':998, 'wind_speed':5.5,'condition':'Sunny',        'visibility':12},
    ]
    print(f'Fallback data loaded for {len(weather_records)} cities')
else:
    print(f'Using live API data for {len(weather_records)} cities')

Using live API data for 8 cities

In [ ]:
# ============================================================
# CELL 16 — TRANSFORM: Build DataFrame from API results
# ============================================================

weather_df = pd.DataFrame(weather_records)
# pd.DataFrame() converts a list of dictionaries into a DataFrame
# Each dictionary becomes one row
# Each dictionary key becomes a column name
# This is the standard pattern for API → DataFrame conversion

print('Weather DataFrame created:')
print(weather_df.to_string(index=False))
print(f'\nShape: {weather_df.shape}')
print(f'Missing values: {weather_df.isnull().sum().sum()}')
print(f'\nData types:')
print(weather_df.dtypes)

Weather DataFrame created:
     city  temperature  feels_like  humidity  pressure  wind_speed        condition  visibility
   Mumbai         31.0        37.6        70      1010        4.12             Haze           3
    Delhi         36.0        34.4        21       999        1.54             Haze           5
Bangalore         24.6        25.2        79      1013        4.47 Scattered Clouds           6
  Chennai         31.7        38.7        73      1008        4.12             Haze           5
Hyderabad         30.2        31.6        51      1008        4.12             Haze           5
  Kolkata         27.0        29.5        78      1006        5.14             Haze           3
     Pune         29.1        29.4        47      1011        4.85 Scattered Clouds          10
   Jaipur         37.6        36.2        20      1003        3.60             Haze           3

Shape: (8, 8)
Missing values: 0

Data types:
city            object
temperature    float64
feels_like     float64
humidity         int64
pressure         int64
wind_speed     float64
condition       object
visibility       int64
dtype: object

In [ ]:
# ============================================================
# CELL 17 — TRANSFORM: Analysis on weather data
# ============================================================

print('=' * 50)
print('  WEATHER ANALYSIS REPORT — 8 INDIAN CITIES')
print('=' * 50)

# Hottest and coldest city
hottest = weather_df.loc[weather_df['temperature'].idxmax()]
coldest = weather_df.loc[weather_df['temperature'].idxmin()]
# .idxmax() returns the INDEX of the maximum value
# .idxmin() returns the INDEX of the minimum value
# df.loc[index] returns the full row at that index

print(f"\nHottest city : {hottest['city']} at {hottest['temperature']}°C")
print(f"Coldest city : {coldest['city']} at {coldest['temperature']}°C")
print(f"Most humid   : {weather_df.loc[weather_df['humidity'].idxmax()]['city']} "
      f"({weather_df['humidity'].max()}%)")

# Summary statistics
print(f"\nAverage temperature : {weather_df['temperature'].mean():.1f}°C")
print(f"Average humidity    : {weather_df['humidity'].mean():.1f}%")
print(f"Average wind speed  : {weather_df['wind_speed'].mean():.1f} m/s")

# Rankings
print('\nCities ranked by temperature (hottest first):')
ranked = weather_df[['city','temperature','humidity']].sort_values('temperature', ascending=False)
print(ranked.to_string(index=False))

==================================================
  WEATHER ANALYSIS REPORT — 8 INDIAN CITIES
==================================================

Hottest city : Jaipur at 37.6°C
Coldest city : Bangalore at 24.6°C
Most humid   : Bangalore (79%)

Average temperature : 30.9°C
Average humidity    : 54.9%
Average wind speed  : 4.0 m/s

Cities ranked by temperature (hottest first):
     city  temperature  humidity
   Jaipur         37.6        20
    Delhi         36.0        21
  Chennai         31.7        73
   Mumbai         31.0        70
Hyderabad         30.2        51
     Pune         29.1        47
  Kolkata         27.0        78
Bangalore         24.6        79

In [ ]:
# ============================================================
# CELL 18 — LOAD: Save weather data to CSV
# ============================================================

weather_df.to_csv('weather_data.csv', index=False)
# Saves the cleaned, structured weather DataFrame to a CSV file
# This file can be loaded into SQLite (Day 2 skills) or used in ML (Day 5)

print('Weather data saved to: weather_data.csv')
print('\nWeather ETL Pipeline: COMPLETE')
print('  EXTRACT   → OpenWeatherMap API called for 8 cities')
print('  TRANSFORM → JSON parsed, DataFrame built, units converted')
print('  LOAD      → weather_data.csv saved')

Weather data saved to: weather_data.csv

Weather ETL Pipeline: COMPLETE
  EXTRACT   → OpenWeatherMap API called for 8 cities
  TRANSFORM → JSON parsed, DataFrame built, units converted
  LOAD      → weather_data.csv saved

# **MINI PROJECT 1**

In [74]:
import requests
import pandas as pd

# --- EXTRACT --- #

API_KEY = '8ce86da271c6e3a978c2359e88324349' # Replace with your actual OpenWeatherMap API key
BASE_URL = 'http://api.openweathermap.org/data/2.5/weather'
CITIES = ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Hyderabad', 'Kolkata', 'Pune', 'Jaipur']

def fetch_weather(city, API_KEY):
    """
    Fetch current weather data for a given city.
    Returns a dictionary with weather metrics, or None on failure.
    """
    params = {
        'q':     city,
        'appid': API_KEY,
        'units': 'metric'
    }
    try:
        response = requests.get(BASE_URL, params=params, timeout=10)
        if response.status_code == 200:
            data = response.json()
            return {
                'city':        city,
                'temperature': round(data['main']['temp'], 1),
                'feels_like':  round(data['main']['feels_like'], 1),
                'humidity':    data['main']['humidity'],
                'pressure':    data['main']['pressure'],
                'wind_speed':  data['wind']['speed'],
                'condition':   data['weather'][0]['description'].title(),
                'visibility':  data.get('visibility', 0) // 1000
            }
        else:
            print(f'  ERROR {response.status_code} for {city}: {response.json().get("message","unknown error")}')
            return None

    except requests.exceptions.ConnectionError:
        print(f'  CONNECTION ERROR for {city} — check internet connection')
        return None
    except requests.exceptions.Timeout:
        print(f'  TIMEOUT for {city} — API did not respond in 10 seconds')
        return None


print('Calling Weather API...')
weather_records = []
for city in CITIES:
    print(f'  Fetching: {city}...', end='')
    record = fetch_weather(city, API_KEY)
    if record:
        weather_records.append(record)
        print(f' {record["temperature"]}°C, {record["condition"]}')
    else:
        print(' FAILED')

print(f'\nSuccessfully fetched: {len(weather_records)}/{len(CITIES)} cities')

# --- TRANSFORM --- #

# Create DataFrame from API results
weather_df = pd.DataFrame(weather_records)

print('\nWeather DataFrame created and data cleaned (structured):')
print(weather_df.head())
print(f'Shape: {weather_df.shape}')
print(f'Missing values: {weather_df.isnull().sum().sum()}')

# --- LOAD --- #

# Save the DataFrame to a CSV file
output_filename = 'weather_data_etl_output.csv'
weather_df.to_csv(output_filename, index=False)

print(f'\nWeather data saved to: {output_filename}')
print('\nWeather Data ETL Pipeline: COMPLETE')
print('  EXTRACT   → OpenWeatherMap API called')
print('  TRANSFORM → JSON parsed, DataFrame built, units converted')
print(f'  LOAD      → {output_filename} saved')

Calling Weather API...
  Fetching: Mumbai... 31.0°C, Haze
  Fetching: Delhi... 29.1°C, Thunderstorm
  Fetching: Bangalore... 23.4°C, Scattered Clouds
  Fetching: Chennai... 31.0°C, Few Clouds
  Fetching: Hyderabad... 30.7°C, Broken Clouds
  Fetching: Kolkata... 27.0°C, Haze
  Fetching: Pune... 26.8°C, Clear Sky
  Fetching: Jaipur... 33.6°C, Dust

Successfully fetched: 8/8 cities

Weather DataFrame created and data cleaned (structured):
        city  temperature  feels_like  humidity  pressure  wind_speed  \
0     Mumbai         31.0        37.6        70      1010        3.60
1      Delhi         29.1        30.2        54      1002        6.17
2  Bangalore         23.4        24.0        84      1014        4.12
3    Chennai         31.0        38.0        89      1009        5.14
4  Hyderabad         30.7        34.8        62      1006        4.12

          condition  visibility
0              Haze           4
1      Thunderstorm           4
2  Scattered Clouds           6
3        Few Clouds           6
4     Broken Clouds           6
Shape: (8, 8)
Missing values: 0

Weather data saved to: weather_data_etl_output.csv

Weather Data ETL Pipeline: COMPLETE
  EXTRACT   → OpenWeatherMap API called
  TRANSFORM → JSON parsed, DataFrame built, units converted
  LOAD      → weather_data_etl_output.csv saved

# **MINI PROJECT 2**

In [75]:
import pandas as pd

# --- CONFIGURATION --- #
excel_file_path = 'employee_salary_data.xlsx' # Make sure this Excel file is uploaded or accessible
output_csv_file = 'cleaned_employee_salary.csv'

# --- EXTRACT --- #
print('--- Starting Employee Salary ETL Project ---')

try:
    # Attempt to load data from Excel
    df_raw = pd.read_excel(excel_file_path)
    print(f'Successfully loaded data from {excel_file_path}. Shape: {df_raw.shape}')
except FileNotFoundError:
    print(f'Warning: {excel_file_path} not found. Creating dummy data for demonstration.')
    # Create a dummy DataFrame if the Excel file is not found
    data = {
        'Employee ID': [101, 102, 103, 104, 105, 101, 106, 107, 108],
        'Name': ['Alice Smith', 'Bob Johnson', 'Charlie Brown', 'Diana Prince', 'Eve Adams', 'Alice Smith', 'Frank White', 'Grace Black', 'Harry Green'],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'HR', 'HR', 'IT', 'Finance', 'Marketing'],
        'Monthly Salary': [5000, 6000, 7500, 5500, 5200, 5000, 6200, 7800, 5800]
    }
    df_raw = pd.DataFrame(data)
    print(f'Dummy DataFrame created. Shape: {df_raw.shape}')

df = df_raw.copy() # Create a working copy

# --- TRANSFORM --- #
print('\n--- Data Transformation ---')

# 1. Remove duplicate records
print(f'Before dropping duplicates: {len(df)} rows')
duplicates_before = df.duplicated().sum()
df.drop_duplicates(inplace=True)
print(f'Removed {duplicates_before} duplicate rows. After dropping duplicates: {len(df)} rows')

# 2. Calculate Yearly Salary
if 'Monthly Salary' in df.columns:
    df['Yearly Salary'] = df['Monthly Salary'] * 12
    print('Calculated "Yearly Salary" based on "Monthly Salary".')
elif 'salary' in df.columns:
    df['Yearly Salary'] = df['salary'] * 12
    print('Calculated "Yearly Salary" based on "salary".')
else:
    print('Could not find "Monthly Salary" or "salary" column to calculate yearly salary.')

print('\nTransformed Data (first 5 rows):')
print(df.head())
print(f'Final DataFrame shape after transformations: {df.shape}')
print(f'Missing values after transformations: {df.isnull().sum().sum()}')

# --- LOAD --- #
print('\n--- Data Loading ---')
df.to_csv(output_csv_file, index=False)
print(f'Cleaned employee salary data saved to: {output_csv_file}')

print('\n--- Employee Salary ETL Project: COMPLETE ---')
print('  EXTRACT   → Data loaded from Excel (or dummy data generated)')
print('  TRANSFORM → Duplicates removed, Yearly Salary calculated')
print(f'  LOAD      → {output_csv_file} saved')

--- Starting Employee Salary ETL Project ---
Warning: employee_salary_data.xlsx not found. Creating dummy data for demonstration.
Dummy DataFrame created. Shape: (9, 4)

--- Data Transformation ---
Before dropping duplicates: 9 rows
Removed 1 duplicate rows. After dropping duplicates: 8 rows
Calculated "Yearly Salary" based on "Monthly Salary".

Transformed Data (first 5 rows):
   Employee ID           Name Department  Monthly Salary  Yearly Salary
0          101    Alice Smith         HR            5000          60000
1          102    Bob Johnson         IT            6000          72000
2          103  Charlie Brown    Finance            7500          90000
3          104   Diana Prince  Marketing            5500          66000
4          105      Eve Adams         HR            5200          62400
Final DataFrame shape after transformations: (8, 5)
Missing values after transformations: 0

--- Data Loading ---
Cleaned employee salary data saved to: cleaned_employee_salary.csv

--- Employee Salary ETL Project: COMPLETE ---
  EXTRACT   → Data loaded from Excel (or dummy data generated)
  TRANSFORM → Duplicates removed, Yearly Salary calculated
  LOAD      → cleaned_employee_salary.csv saved