In [10]:
import pandas as pd
print("pandas import successfully")

pandas import successfully

In [11]:
df=pd.read_csv('student_performance.csv')

In [12]:
df.head()
#first five rows

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [13]:
df.tail()
#last five rows

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [14]:
df.shape
#row,col

(30, 13)

In [15]:
df.shape[0]
#rows

30

In [16]:
df.shape[1]
#cols

13

In [17]:
df.columns.tolist()
#print all the column name

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [18]:
df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [19]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [20]:
df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [21]:
df.isnull().sum().sum()

np.int64(0)

In [22]:
df['age']

0     19
1     20
2     19
3     20
4     19
5     20
6     21
7     19
8     20
9     19
10    20
11    19
12    21
13    20
14    19
15    20
16    21
17    19
18    20
19    19
20    20
21    19
22    21
23    20
24    19
25    20
26    21
27    19
28    20
29    19
Name: age, dtype: int64

In [23]:
df['name']

0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [24]:
df['department']

0     Computer Science
1     Computer Science
2          Electronics
3           Mechanical
4     Computer Science
5          Electronics
6                Civil
7     Computer Science
8           Mechanical
9     Computer Science
10         Electronics
11               Civil
12    Computer Science
13          Mechanical
14    Computer Science
15         Electronics
16               Civil
17    Computer Science
18          Mechanical
19    Computer Science
20         Electronics
21    Computer Science
22               Civil
23          Mechanical
24    Computer Science
25         Electronics
26    Computer Science
27               Civil
28          Mechanical
29    Computer Science
Name: department, dtype: object

In [25]:
df['department'].unique()
#unique values in the col

array(['Computer Science', 'Electronics', 'Mechanical', 'Civil'],
      dtype=object)

In [26]:
df['department'].value_counts()
#like the frequency of the values in the col

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

Filtering

In [27]:
df[df['department']=='Computer Science']

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [28]:
cse_student = df[df['department']=='Computer Science']

In [29]:
len(cse_student)

13

In [30]:
high_attendance=df[df['attendance_percentage']>90]

In [31]:
len(high_attendance)

10

In [32]:
print(high_attendance)

    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
7         1008     Divya Singh   19  Female  Computer Science         2
9         1010      Ananya Das   19  Female  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
24        1025       Amit Bose   19    Male  Computer Science         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
3           70             80             75                 48
7           88             91             84                 93
9           95             89             90                 97
13          74             78             82                 51
15          87             83             86                 69
17          90             87             85                 92
21          93             90             88                 96
24          86             82             79                 89
29          91             93             87                 94

    attendance_percentage       city  admission_year
0                      92     Mumbai            2023
3                      95  Hyderabad            2023
7                      96    Lucknow            2023
9                      98    Kolkata            2023
13                     91   Thrissur            2023
15                     93       Agra            2023
17                     94     Nagpur            2023
21                     97      Surat            2023
24                     91    Kolkata            2023
29                     95       Agra            2023

In [33]:
print(high_attendance[['student_id','name','department','attendance_percentage']])

    student_id            name        department  attendance_percentage
0         1001    Aarav Sharma  Computer Science                     92
3         1004     Sneha Reddy        Mechanical                     95
7         1008     Divya Singh  Computer Science                     96
9         1010      Ananya Das  Computer Science                     98
13        1014   Kavya Nambiar        Mechanical                     91
15        1016    Ritu Agarwal       Electronics                     93
17        1018  Swati Kulkarni  Computer Science                     94
21        1022     Tanvi Mehta  Computer Science                     97
24        1025       Amit Bose  Computer Science                     91
29        1030  Akanksha Yadav  Computer Science                     95

In [34]:
total_score=df['math_score']+df['science_score']+df['english_score']+df['programming_score']
print(total_score)

0     326
1     325
2     255
3     273
4     356
5     246
6     247
7     356
8     236
9     371
10    295
11    262
12    334
13    285
14    280
15    325
16    210
17    354
18    252
19    327
20    259
21    367
22    228
23    287
24    336
25    285
26    325
27    232
28    271
29    365
dtype: int64

In [35]:
df['total_score']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']
top_student=df.loc[df['total_score'].idxmax()]
print(top_student)

student_id                           1010
name                           Ananya Das
age                                    19
gender                             Female
department               Computer Science
semester                                2
math_score                             95
science_score                          89
english_score                          90
programming_score                      97
attendance_percentage                  98
city                              Kolkata
admission_year                       2023
total_score                           371
Name: 9, dtype: object

In [36]:
top_student=df.loc[df['total_score'].idxmax()]
print(top_student)

student_id                           1010
name                           Ananya Das
age                                    19
gender                             Female
department               Computer Science
semester                                2
math_score                             95
science_score                          89
english_score                          90
programming_score                      97
attendance_percentage                  98
city                              Kolkata
admission_year                       2023
total_score                           371
Name: 9, dtype: object

In [37]:
top_student['name']

'Ananya Das'

In [38]:
top_student['department']

'Computer Science'

In [39]:
top_student['total_score']

np.int64(371)

In [40]:
top_student['attendance_percentage']

np.int64(98)

In [41]:
dept_avg=df.groupby('department')['total_score'].mean().round(2)

In [42]:
df_sorted=df.sort_values(by='total_score', ascending=False)
print(df_sorted.head())

    student_id            name  age  gender        department  semester  \
9         1010      Ananya Das   19  Female  Computer Science         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2
4         1005      Arjun Nair   19    Male  Computer Science         2
7         1008     Divya Singh   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
9           95             89             90                 97
21          93             90             88                 96
29          91             93             87                 94
4           92             88             81                 95
7           88             91             84                 93

    attendance_percentage     city  admission_year  total_score
9                      98  Kolkata            2023          371
21                     97    Surat            2023          367
29                     95     Agra            2023          365
4                      90    Kochi            2023          356
7                      96  Lucknow            2023          356

# **Practice Question**

1.how many students are from the electronics department

In [43]:
electronics_dep=df[df['department']=='Electronics']

In [44]:
len(electronics_dep)

6

2.what is the avg attendance of the electronics department

In [45]:
avg_attendance_electronics = electronics_dep['attendance_percentage'].mean().round(2)

In [46]:
avg_attendance_electronics

np.float64(80.33)

3.who is the student with the lowest programming score

In [47]:
lowest_programming_student = df.loc[df['programming_score'].idxmin()]
print(lowest_programming_student)

student_id                       1017
name                     Manoj Pandey
age                                21
gender                           Male
department                      Civil
semester                            2
math_score                         56
science_score                      61
english_score                      55
programming_score                  38
attendance_percentage              65
city                            Patna
admission_year                   2023
total_score                       210
Name: 16, dtype: object

4.how many student scored above 80 in math

In [48]:
math_topper=df[df['math_score']>80]

In [49]:
len(math_topper)

11

5.what is the average total_score for students with attendance above 90%

In [50]:
attendance_score=df[df['attendance_percentage']>90]

In [51]:
average_attendance_score_above_90=attendance_score['total_score'].mean().round(2)

In [52]:
print(average_attendance_score_above_90)

335.8

# **MINI PROJECT**
## **Student Data Explorer**

Objective:
Create a Student Performance Explorer using python and Pandas to analyse student data and generate a detailed report.

Dataset Columns:
name
gender
departments
math_score
programming_score
attendance_percentage
toal_score

Tasks to perform:

1.Display project file
Print a formatted title with seperator lines.

2.Dataset Overview:

Display:

-Total number of students

-Total number of colums

-Number of unique departments

3.Department wise Analysis:

Display the count of students in each department.

4.Score Analysis:

Find and display:

-Highest math score

-Lowest math score

-Average math score

-Average programming score

-Average attendance percentage

5.Gender wise Analysis:

Calculate and display average total score grouped by gender

6.Top Performers:

Calculate the top 5 students based on total_score

show:

-Student Name

-Department

-Total Score

7.Attendance Analysis

Find students whose attendance is below 75%

Display:

-Name

-Department

-Attendance Percentage

If all students have attendance above 75%

print a suitable message

Concepts to Use:

-pandas, DataFrame, groupby(), value_count(), mean(), max(), min(), sort_values(), conditional statements, f-strings

1.Display project file Print a formatted title with seperator lines.

#===========================================

#Student Data Explorer Project Report

#===========================================

2.Dataset Overview:

-Total number of students

In [54]:
len(df)

30

-Total number of colums

In [55]:
df.shape[1]

13

-Number of unique departments

In [56]:
departments=df['department'].unique()
len(departments)

4

3.Department wise Analysis:

Display the count of students in each department.

In [57]:
print(departments)

['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [58]:
student_cse=df[df['department']=='Computer Science']
len(student_cse)

13

In [59]:
student_ece=df[df['department']=='Electronics']
len(student_ece)

6

In [60]:
student_mec=df[df['department']=='Mechanical']
len(student_mec)

6

In [61]:
student_civ=df[df['department']=='Civil']
len(student_civ)

5

In [62]:
df['department'].value_counts()

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

4.Score Analysis:

-Hightest maths score

In [63]:
high_math_score=df['math_score'].max()
print(high_math_score)

95

-Lowest math score

In [64]:
low_math_score=df['math_score'].min()
print(low_math_score)

56

-average math score

In [65]:
avg_math_score=df['math_score'].mean().round(2)
print(avg_math_score)

76.07

-average programming score

In [66]:
avg_prog_score=df['programming_score'].mean().round(2)
print(avg_prog_score)

67.6

-average attendance score

In [67]:
avg_attendance_score=df['attendance_percentage'].mean().round(2)
print(avg_attendance_score)

84.5

5.Gender wise Analysis:

In [68]:
avg_total_score_gender=df.groupby('gender')

In [69]:

print(avg_total_score_gender)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7a717e723560>

# **Mini Project**

In [72]:
import pandas as pd

print("-" * 60)
print(f"{'STUDENT DATA EXPLORER':^60}")
print(f"{'Mini Project Report':^60}")
print("-" * 60)

# =================== 1. PROJECT TITLE DONE ABOVE ===================


# =================== 2. DATASET OVERVIEW ===================
print("\n" + "=" * 50)
print("        DATASET OVERVIEW")
print("=" * 50)

print(f"Total number of students   : {len(df)}")
print(f"Total number of columns    : {len(df.columns)}")
print(f"Number of unique departments: {df['department'].nunique()}")


# =================== 3. DEPARTMENT WISE ANALYSIS ===================
print("\n" + "=" * 50)
print("   DEPARTMENT WISE ANALYSIS")
print("=" * 50)

dept_counts = df["department"].value_counts()
for department, count in dept_counts.items():
    print(f"{department:<20} : {count} students")


# =================== 4. SCORE ANALYSIS ===================
print("\n" + "=" * 50)
print("         SCORE ANALYSIS")
print("=" * 50)

print(f"Highest math score              : {df['math_score'].max():>3}")
print(f"Lowest math score               : {df['math_score'].min():>3}")
print(f"Average math score              : {df['math_score'].mean():5.2f}")
print(f"Average programming score       : {df['programming_score'].mean():5.2f}")
print(f"Average attendance percentage   : {df['attendance_percentage'].mean():5.2f} %")


# =================== 5. GENDER WISE ANALYSIS ===================
print("\n" + "=" * 50)
print("   GENDER WISE ANALYSIS (Average Total Score)")
print("=" * 50)

# Create total_score = math + programming
df["total_score"] = df["math_score"] + df["programming_score"]
gender_avg = df.groupby("gender")["total_score"].mean()

for gender, avg_score in gender_avg.items():
    print(f"{gender:<8} : {avg_score:6.2f}")


# =================== 6. TOP PERFORMERS ===================
print("\n" + "=" * 50)
print("             TOP 5 PERFORMERS")
print("=" * 50)

top_5 = df.sort_values("total_score", ascending=False).head(5)[["name", "department", "total_score"]]
print(f"{'Name':<20} {'Department':<15} {'Total Score'}")
print("-" * 50)
for _, row in top_5.iterrows():
    print(f"{row['name']:<20} {row['department']:<15} {row['total_score']}")


# =================== 7. ATTENDANCE ANALYSIS ===================
print("\n" + "=" * 50)
print("         ATTENDANCE ANALYSIS (Below 75%)")
print("=" * 50)

low_att = df[df["attendance_percentage"] < 75]
if low_att.empty:
    print("All students have attendance above or equal to 75%.")
else:
    print(f"{'Name':<20} {'Department':<15} {'Attendance %'}")
    print("-" * 50)
    for _, row in low_att.iterrows():
        print(f"{row['name']:<20} {row['department']:<15} {row['attendance_percentage']:>10}%")

------------------------------------------------------------
                   STUDENT DATA EXPLORER
                    Mini Project Report
------------------------------------------------------------

==================================================
        DATASET OVERVIEW
==================================================
Total number of students   : 30
Total number of columns    : 14
Number of unique departments: 4

==================================================
   DEPARTMENT WISE ANALYSIS
==================================================
Computer Science     : 13 students
Electronics          : 6 students
Mechanical           : 6 students
Civil                : 5 students

==================================================
         SCORE ANALYSIS
==================================================
Highest math score              :  95
Lowest math score               :  56
Average math score              : 76.07
Average programming score       : 67.60
Average attendance percentage   : 84.50 %

==================================================
   GENDER WISE ANALYSIS (Average Total Score)
==================================================
Female   : 148.67
Male     : 138.67

==================================================
             TOP 5 PERFORMERS
==================================================
Name                 Department      Total Score
--------------------------------------------------
Ananya Das           Computer Science 192
Tanvi Mehta          Computer Science 189
Arjun Nair           Computer Science 187
Akanksha Yadav       Computer Science 185
Swati Kulkarni       Computer Science 182

==================================================
         ATTENDANCE ANALYSIS (Below 75%)
==================================================
Name                 Department      Attendance %
--------------------------------------------------
Meera Joshi          Electronics             72%
Rahul Mishra         Mechanical              68%
Manoj Pandey         Civil                   65%
Harish Pillai        Electronics             74%
Sanjay Dubey         Civil                   70%
Sunita Pillai        Civil                   73%